Windows+Cmake
vysheng/tl-parser pull request #17
Opened 2020-12-31 13:57 UTC by arves100

#16

2021-01-02 23:50 UTC, levlam requested changes

2021-01-02 23:50 UTC, levlam commented on CMakeLists.txt
> +project(tl-parser)
Could you specify "LANGUAGES C".

2021-01-02 23:50 UTC, levlam commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0)
Could you add "FATAL_ERROR"?

2021-01-02 23:50 UTC, levlam commented on CMakeLists.txt
> +		set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SUBSYSTEM:CONSOLE")
Isn't "CONSOLE" a default value of `/SUBSYSTEM`?

2021-01-02 23:50 UTC, levlam commented on CMakeLists.txt
> +set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG .)
This shouldn't be needed. Other CMake projects can use target's name instead of full path to tl-parser executable.

2021-01-02 23:50 UTC, levlam commented on crc32.h
> +extern unsigned long long crc64_table[256];
crc64 mentions can be deleted.

2021-01-02 23:50 UTC, levlam commented on crc32.h
> +int crc32_check_and_repair (void *input, int l, unsigned *input_crc32, int force_exit);
This function and other unused functions can be deleted.

2021-01-07 15:21 UTC, arves100 commented
@levlam updated the new commit with the changes you requested

2021-01-07 16:29 UTC, levlam commented
Squashed commit was fine.

2021-01-07 19:53 UTC, merged

2022-07-15 18:23 UTC, Dieptran123 reviewed
![Screenshot_2022-07-13-22-28-42-17_238abb266a18fee164daf271175dc060](https://user-images.githubusercontent.com/109226088/179287175-6a7eaacd-79d6-45f6-99c1-a17d07ac56ec.png)

2022-07-15 18:25 UTC, Dieptran123 reviewed
https://www.google.com/aclk?sa=L&ai=DChcSEwixz8GTwvv4AhVPQWAKHdUcAcIYABABGgJ0bQ&ae=1&sig=AOD64_3OyHAAeZ-f0Q61Z05Nt43KUpXcMQ&q=&ved=2ahUKEwjM2LuTwvv4AhVIdXAKHXTYBCEQ3ooFegQIBRAB&adurl=intent://details%3Fid%3Dcom.play8usclub.game.bai.casino%26inline%3Dtrue%26enifd%3DAMO2QMabUsk5CA4_9nOdLMaemsJLOmLPy8lsqhqeYxrBIn4m22gAn-AeF6Xdfs7awF82a70ENBtcvdjNHB3iVuZv24LsZBYR3u6_k_344dDgDRsOoTGNUAG05hInNd7GXr9PAYU-sA%26referrer%3Dgclid%253DCjwKCAjwoMSWBhAdEiwAVJ2ndproVP-nuLnepKkht7637WgbkInJWgtnwmBSvTgXfSDmYrV_2R6ZwhoCg74QAvD_BwE%26gref%3DEkQKPAoICPCgxJYGEB0SLABUnad2muhU_6e4ud6kqSG3vrftaBuQiclaC2fCYFK9OBd9IOZitX_ZHpnCGgKDvhAC8P8HARjp68XfKCIIGAUgATABOAc%23Intent%3Bscheme%3Dmarket%3Bpackage%3Dcom.android.vending%3Bend%3B

2022-07-15 18:27 UTC, Dieptran123 commented
> Cam kết bị ép là tốt

2022-07-15 18:27 UTC, Dieptran123 commented
![Screenshot_2022-07-15-18-33-50-55](https://user-images.githubusercontent.com/109226088/179288241-ab2f69e4-cec1-44c1-bc99-0c153cf517cf.png)

2025-09-10 18:41 UTC, jhonjhoncarcallas89-dotcom commented
One try to the

2025-09-10 18:41 UTC, jhonjhoncarcallas89-dotcom commented
One the try for me